package com.gozar.app.core

/**
 * Routing lists are embedded rather than downloaded as sing-box `rule_set`
 * bundles on purpose: a remote rule set has to be fetched before the tunnel is
 * usable, and on a censored network that fetch is exactly what fails. These
 * cover the traffic that actually matters day to day, at zero startup cost.
 */
object RoutingLists {

    /** Domains that should never leave the country through a foreign proxy. */
    val iranDomainSuffixes: List<String> = listOf(
        ".ir",
        "aparat.com",
        "digikala.com",
        "divar.ir",
        "snapp.ir",
        "snapp.market",
        "tapsi.cab",
        "bank-maskan.ir",
        "shaparak.ir",
        "sep.ir",
        "sadad.shaparak.ir",
        "irancell.ir",
        "mci.ir",
        "rightel.ir",
        "cafebazaar.ir",
        "myket.ir",
        "varzesh3.com",
        "namasha.com",
        "filimo.com",
        "namava.ir",
        "telewebion.com",
        "blogfa.com",
        "mihanblog.com",
        "zoomit.ir",
        "faradars.org",
        "quera.org",
        "arvancloud.ir",
        "arvancloud.com",
        "abrarvan.com",
        "iranserver.com",
        "parspack.com",
        "mizbanfa.net",
        "hamrahaval.ir",
        "eitaa.com",
        "rubika.ir",
        "splus.ir",
        "bale.ai",
        "soroush-hamrah.ir",
        "gap.im",
        "irancell.com",
        "shatel.ir",
        "asiatech.ir",
        "pishgaman.net",
        "respina.net",
        "sahab.ir",
        "setare.com",
        "tic.ir",
        "iranair.com",
        "alibaba.ir",
        "flytoday.ir",
        "snapptrip.com",
        "banki.ir",
        "bmi.ir",
        "bpi.ir",
        "bsi.ir",
        "sb24.ir",
        "enbank.ir",
        "sinabank.ir",
        "ba24.ir",
        "day24.ir",
        "refahbank.ir",
        "tejaratbank.ir",
        "bankmellat.ir",
        "bankmelli.ir",
    )

    /** Common advertising and telemetry hosts, used by the optional ad blocker. */
    val adDomainSuffixes: List<String> = listOf(
        "doubleclick.net",
        "googleadservices.com",
        "googlesyndication.com",
        "google-analytics.com",
        "googletagmanager.com",
        "googletagservices.com",
        "adservice.google.com",
        "adnxs.com",
        "adsrvr.org",
        "rubiconproject.com",
        "pubmatic.com",
        "criteo.com",
        "criteo.net",
        "taboola.com",
        "outbrain.com",
        "scorecardresearch.com",
        "quantserve.com",
        "moatads.com",
        "amazon-adsystem.com",
        "adcolony.com",
        "applovin.com",
        "unityads.unity3d.com",
        "chartboost.com",
        "vungle.com",
        "inmobi.com",
        "startappservice.com",
        "mopub.com",
        "flurry.com",
        "crashlytics.com",
        "appsflyer.com",
        "adjust.com",
        "branch.io",
        "kochava.com",
        "supersonicads.com",
        "smaato.net",
        "yieldmo.com",
        "openx.net",
        "casalemedia.com",
        "bidswitch.net",
        "sharethrough.com",
        "teads.tv",
        "zedo.com",
        "propellerads.com",
        "popads.net",
        "adsterra.com",
        "revcontent.com",
        "mgid.com",
        "yandex-metrica.com",
        "mc.yandex.ru",
        "hotjar.com",
        "mixpanel.com",
        "segment.io",
        "amplitude.com",
        "fullstory.com",
        "clarity.ms",
    )
}
